project_name: grafana-ds-convert
before:
  hooks:
    - go mod tidy
builds:
  - 
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
      - freebsd
      - openbsd
      - solaris
      - illumos
    goarch:
      - amd64
      - arm64
      - arm
    ignore:
      -
        goarch: 386
      - goos: freebsd
        goarch: arm
      - goos: openbsd
        goarch: arm64
      - goos: openbsd
        goarch: arm

archives:
  - 
    id: default
    name_template: "{{.ProjectName}}_{{.Tag}}_{{.Os}}_{{.Arch}}"
    format: tar.gz
    replacements:
      amd64: x86_64
    format_overrides:
      -
        goos: windows
        format: zip
    files:
      - LICENSE
      - README.md

release:
    github:
        owner: circonus
        name: grafana-ds-convert

    prerelease: auto

checksum:
  name_template: "{{.ProjectName}}_checksums.txt"

snapshot:
  name_template: "SNAPSHOT-{{.Commit}}"